Add safe guard for marketplace publish
Tag must exist on master branch

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,7 +58,7 @@ jobs:
               echo "Append prerelease to version: -${PRERELEASE}"
               npx json -I -f package.json -e 'this.version=this.version.replace(/$/,"-'${PRERELEASE}'")'
             fi
-            if [ ${TAG_VERSION} = NO-TAG -o "${TAG_VERSION}" = "${VERSION}"  ]
+            if [ ${TAG_VERSION} = NO-TAG -o "${TAG_VERSION}" = "${VERSION}" ]
             then
               VERSION=$(node -p 'require("./package.json").version')
               echo "Using version: ${VERSION}"
@@ -100,7 +100,7 @@ jobs:
             fi
             GHR_ARGS="-t ${GITHUB_TOKEN} ${EXTRA_RELEASE_OPTIONS} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} /tmp/artifacts/"
 
-            if [ -z "${CIRCLE_BUILD_NUM}" ]
+            if [ "${IS_LOCAL}" = YES ]
             then
               echo "Dry ghr ${GHR_ARGS}"
             else
@@ -120,7 +120,24 @@ jobs:
           key: dependency-cache-{{ checksum "package.json" }}
       - run:
           name: Publish to the marketplace
-          command: npx vsce publish --packagePath /tmp/artifacts/calva-$(node -p 'require("./package.json").version').vsix -p ${PUBLISH_TOKEN}
+          command: |
+            TAGGED_BRANCH=$(git branch --contains tags/${CIRCLE_TAG})
+            if [[ "${TAGGED_BRANCH/\*/}" =~ master ]]
+            then
+              echo "Tag is on master. Proceeding with publish."
+            else
+              echo >&2 "FATAL! Tag is not on master. Aborting."
+              exit 1
+            fi
+
+            VSCE_CMD="vsce publish --packagePath /tmp/artifacts/calva-$(node -p 'require("./package.json").version').vsix -p ${PUBLISH_TOKEN}"
+
+            if [ "${IS_LOCAL}" = YES ]
+            then
+              echo "Dry npx ${VSCE_CMD}"
+            else
+              npx ${VSCE_CMD}
+            fi
 workflows:
   version: 2
   build-test:
